# Generated by Django 5.0.6 on 2024-06-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('VIN', models.CharField(max_length=17, unique=True)),
                ('odometer', models.FloatField(default=0)),
                ('refresh_token', models.CharField(max_length=255)),
            ],
        ),
    ]
